# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='request_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='request_key',
            field=models.CharField(default='None', max_length=32),
        ),
    ]
