# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_device_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='app.UserProfile'),
            preserve_default=False,
        ),
    ]
