# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170412_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='newDevice', max_length=32, unique=True),
        ),
    ]
